export interface ServiceItem {
  num: string;
  tag: string;
  title: string;
  desc: string;
  body: string;
  items: string[];
  image: string;
  credit: string;
  creditHref: string;
}

export const SERVICES: ServiceItem[] = [
  {
    num: "01",
    tag: "Ocean · Air · Road · Rail",
    title: "Freight Forwarding",
    desc: "Seamless Freight Forwarding Across Domestic & International Markets",
    body: "Efficient freight forwarding is the foundation of a successful supply chain. We coordinate the movement of cargo across sea, air, road, and rail through trusted transportation networks, choosing the mode that suits your cargo, destination, transit time, and budget. That means timely deliveries, smooth communication, and complete visibility throughout the shipping process.",
    items: [
      "Ocean Freight (FCL / LCL)",
      "Air Freight",
      "Rail Freight",
      "Multimodal Transportation",
      "Logistics from Door to Door",
      "Services from Port to Port",
      "Services from Airport to Airport",
      "Cross Trade Shipments",
      "Buyers Consolidation",
      "Cargo Consolidation",
      "Purchase Order Management",
      "Vendor Coordination",
      "Shipment Planning",
      "Cargo Insurance Assistance",
      "Track & Trace Support",
      "Project Cargo Coordination",
    ],
    image: "/images/services/freight-forwarding.jpg",
    credit: "Logan Voss on Unsplash",
    creditHref: "https://unsplash.com/@loganvoss",
  },
  {
    num: "02",
    tag: "Import · Export · Compliance",
    title: "Customs Clearance",
    desc: "Simplifying Customs. Ensuring Compliance.",
    body: "Customs procedures can often be complex and bound by tight deadlines. Our experienced team assists businesses in navigating documentation, regulatory requirements, and clearance procedures, helping minimize delays and ensuring compliance with applicable regulations.",
    items: [
      "Import Customs Clearance",
      "Export Customs Clearance",
      "Bill of Entry Processing",
      "Shipping Bill Processing",
      "Duty Assessment Assistance",
      "HS Code Classification",
      "Customs Documentation",
      "SEZ Documentation",
      "EOU Documentation",
      "DGFT Assistance",
      "Drawback Processing",
      "High Sea Sale Documentation",
      "Bonding & Clearance from Bond",
      "ATA Carnet Assistance",
      "Documentation for Reimport and Reexport",
      "SVB Support",
      "Customs Compliance Advisory",
    ],
    image: "/images/services/customs-clearance.jpg",
    credit: "Yoav Aziz on Unsplash",
    creditHref: "https://unsplash.com/@yoavaziz",
  },
  {
    num: "03",
    tag: "Storage · Fulfilment",
    title: "Warehousing",
    desc: "Secure Storage Solutions That Support Your Supply Chain",
    body: "Efficient warehousing plays a critical role in inventory management and business continuity. Our warehousing solutions provide secure storage, organized inventory handling, and flexible space to meet changing business requirements.",
    items: [
      "Bonded Warehousing",
      "General Warehousing",
      "Inventory Management",
      "Pick & Pack",
      "Cross Docking",
      "Palletization",
      "Order Fulfilment",
      "Distribution Management",
      "Cargo Consolidation",
      "Deconsolidation",
      "Barcode Management",
      "Value Added Services",
      "Stock Monitoring",
    ],
    image: "/images/services/warehousing.jpg",
    credit: "Vida Huang on Unsplash",
    creditHref: "https://unsplash.com/@rebylulu",
  },
  {
    num: "04",
    tag: "Domestic · Last Mile",
    title: "Transportation",
    desc: "Reliable Transportation You Can Count On",
    body: "Timely transportation is essential to keeping businesses moving. We provide dependable transportation solutions that connect suppliers, manufacturers, distributors, and customers through efficient logistics planning and execution.",
    items: [
      "Full Truck Load (FTL)",
      "Part Truck Load (PTL)",
      "Container Transportation",
      "ODC Transportation",
      "Break Bulk Cargo",
      "First Mile Pickup",
      "Last Mile Delivery",
      "Movement from Factory to Port",
      "Movement from Port to Warehouse",
      "Interstate Transportation",
      "Dedicated Fleet Solutions",
      "Reverse Logistics",
      "Milk Run Distribution",
      "Time Critical Deliveries",
    ],
    image: "/images/services/transportation.jpg",
    credit: "Vitalii Onyshchuk on Unsplash",
    creditHref: "https://unsplash.com/@true_zuzu",
  },
  {
    num: "05",
    tag: "Yard · Equipment",
    title: "Container Handling",
    desc: "Efficient Container Management with Operational Precision",
    body: "From container movement to handling and coordination, we ensure smooth operations throughout the logistics process. Our experienced team works closely with clients and partners to optimize container handling while minimizing operational delays.",
    items: [
      "Empty Container Movement",
      "Laden Container Movement",
      "Container Yard Coordination",
      "ICD Coordination",
      "CFS Coordination",
      "Container Stuffing",
      "Container Unloading",
      "Seal Verification",
      "Container Inspection",
      "Port Coordination",
      "Equipment Planning",
    ],
    image: "/images/services/container-handling.jpg",
    credit: "Haris Illahi on Unsplash",
    creditHref: "https://unsplash.com/@harisillahi",
  },
  {
    num: "06",
    tag: "Advisory · Market Entry",
    title: "Export Consultancy",
    desc: "Helping Businesses Enter Global Markets with Confidence",
    body: "Exporting successfully requires more than transportation. It requires the right guidance. We support businesses by simplifying export procedures, helping them understand documentation requirements, compliance processes, logistics planning, and international trade practices.",
    items: [
      "Export process guidance",
      "Documentation support",
      "Logistics planning",
      "Trade compliance assistance",
      "Market readiness guidance",
      "Export coordination from start to finish",
    ],
    image: "/images/services/export-consultancy.jpg",
    credit: "Ambre Estève on Unsplash",
    creditHref: "https://unsplash.com/@ambresteve",
  },
  {
    num: "07",
    tag: "Road · Land Borders",
    title: "Cross Border Road Solutions",
    desc: "Moving Cargo Into Nepal and Bangladesh by Road",
    body: "We move cargo by road into Nepal and Bangladesh, with road connectivity supporting longer stretches of the journey. Our team coordinates border formalities and cargo transfers along the way.",
    items: [
      "Road Freight to Nepal",
      "Road Freight to Bangladesh",
      "Land Border Coordination",
      "Border Documentation Support",
      "Cargo Transfer at Border Points",
    ],
    image: "/images/services/transportation.jpg",
    credit: "Vitalii Onyshchuk on Unsplash",
    creditHref: "https://unsplash.com/@true_zuzu",
  },
  {
    num: "08",
    tag: "DGFT · Licensing · Incentives",
    title: "DGFT and Licensing",
    desc: "Licensing and Incentives Handled with the DGFT",
    body: "Dealing with the Directorate General of Foreign Trade takes time most exporters cannot spare. We manage your registrations, licence applications, and incentive claims from filing through to approval. Our team keeps your records current and your entitlements in order, so you spend less time chasing paperwork and more time selling to customers.",
    items: [
      "Import Export Code (IEC): registration, updates, and maintenance",
      "Incentive schemes: EPCG, Advance Authorization, RoDTEP, RoSCTL, Duty Drawback",
      "RCMC filing across the Export Promotion Councils",
    ],
    image: "/images/services/customs-clearance.jpg",
    credit: "Yoav Aziz on Unsplash",
    creditHref: "https://unsplash.com/@yoavaziz",
  },
  {
    num: "09",
    tag: "Inspection · Certification",
    title: "Export Inspection",
    desc: "Quality Certification That Clears Foreign Customs",
    body: "Many foreign buyers and customs authorities will not accept goods without official quality certification. We help you obtain the approvals issued before shipment that prove your products meet the entry standards of your destination market. Whether you ship food, farm produce, or industrial cargo, we arrange the checks that let your consignment clear inspection abroad.",
    items: [
      "Health, sanitary, and phytosanitary certificates",
      "Preferential and non preferential Certificates of Origin (COO)",
      "Quality inspection clearances required before goods leave port",
    ],
    image: "/images/services/export-consultancy.jpg",
    credit: "Ambre Estève on Unsplash",
    creditHref: "https://unsplash.com/@ambresteve",
  },
  {
    num: "10",
    tag: "Coir · RCMC · Licensing",
    title: "Coir Board",
    desc: "Coir Exports Registered, Licensed, and Documented",
    body: "Exporting coir fibre, yarn, mats, or pith comes with its own set of rules. We handle the industry approvals that let you ship coir products legally and claim the support available to the sector. From membership registration to permit processing, we cover the paperwork so your consignments leave on schedule.",
    items: [
      "Coir Board Registration cum Membership Certificate (RCMC)",
      "Export licensing, quality endorsements, and permit processing",
      "Documentation to claim subsidies and export incentives for coir",
    ],
    image: "/images/services/freight-forwarding.jpg",
    credit: "Logan Voss on Unsplash",
    creditHref: "https://unsplash.com/@loganvoss",
  },
  {
    num: "11",
    tag: "Textiles · Testing · COO",
    title: "Textile Committee",
    desc: "Textiles Tested and Certified for Overseas Buyers",
    body: "Fabrics, garments, and technical textiles need proper verification before they can be sold overseas. We arrange Textile Committee registration and the testing that confirms your material meets buyer requirements. Our team prepares the reports and origin certificates your shipment needs, so your textile exports move through customs without questions about quality.",
    items: [
      "Textile Committee registration and export endorsements",
      "Fabric testing reports and quality certificates before shipment",
      "Generalized System of Preferences (GSP) Certificates of Origin",
    ],
    image: "/images/services/warehousing.jpg",
    credit: "Vida Huang on Unsplash",
    creditHref: "https://unsplash.com/@rebylulu",
  },
  {
    num: "12",
    tag: "EPR · Environmental",
    title: "EPR Compliance",
    desc: "Environmental Compliance That Keeps Imports Moving",
    body: "Companies that import packaging or regulated products carry environmental obligations that customs will check. We manage your EPR compliance so your goods stay within the law and clear the port on time. From first registration to annual returns and recycling targets, we handle the filings that keep your imports free of environmental holds.",
    items: [
      "CPCB and SPCB registration for packaging, electronic waste, batteries, tyres",
      "Annual return filing, recycling target fulfilment, and credit transfers",
      "Import clearance without delays from environmental compliance holds",
    ],
    image: "/images/services/container-handling.jpg",
    credit: "Haris Illahi on Unsplash",
    creditHref: "https://unsplash.com/@harisillahi",
  },
  {
    num: "13",
    tag: "BIS · Standards · Testing",
    title: "BIS Certification",
    desc: "Products Certified to Meet Mandatory Standards",
    body: "Many products cannot be sold in India or abroad until they carry the required safety and quality marks. We guide your goods through Bureau of Indian Standards certification and arrange the testing that supports it. Our team coordinates with laboratories and auditors, so your products meet mandatory standards before they reach the market.",
    items: [
      "Bureau of Indian Standards (BIS) registration and ISI mark approvals",
      "Compulsory Registration Scheme (CRS) and Foreign Manufacturers Scheme (FMCS)",
      "Coordination for lab testing, sample verification, and audit support",
    ],
    image: "/images/services/transportation.jpg",
    credit: "Vitalii Onyshchuk on Unsplash",
    creditHref: "https://unsplash.com/@true_zuzu",
  },
  {
    num: "14",
    tag: "Attestation · Legalization",
    title: "Export Legalization",
    desc: "Documents Legalized for Customs and Payment",
    body: "Foreign customs and banks often require your trade documents to be legalized before they release goods or payment. We handle the attestation of your invoices, packing lists, and certificates through every stage the process demands. With the right stamps in place, you clear customs sooner and collect payment against your letters of credit without holdups.",
    items: [
      "Chamber of Commerce stamping of commercial invoices and packing lists",
      "Apostille and Ministry of External Affairs (MEA) attestations",
      "Embassy legalization for foreign buyers and Letter of Credit compliance",
    ],
    image: "/images/services/customs-clearance.jpg",
    credit: "Yoav Aziz on Unsplash",
    creditHref: "https://unsplash.com/@yoavaziz",
  },
];

export const MARQUEE_SERVICE_NAMES = SERVICES.map((s) => s.title).concat([
  "Global Trade Solutions",
]);
