export interface ServiceItem {
  num: string;
  tag: string;
  title: string;
  desc: string;
  body: string;
  items: string[];
  image: string;
  credit: string;
  creditHref: string;
}

export const SERVICES: ServiceItem[] = [
  {
    num: "01",
    tag: "Ocean · Air · Multimodal",
    title: "Freight Forwarding",
    desc: "Seamless Freight Forwarding Across Domestic & International Markets",
    body: "Efficient freight forwarding is the foundation of a successful supply chain. We coordinate the movement of cargo through trusted transportation networks, ensuring timely deliveries, smooth communication, and complete visibility throughout the shipping process.",
    items: [
      "Ocean Freight (FCL / LCL)",
      "Air Freight",
      "Multimodal Transportation",
      "Door-to-Door Logistics",
      "Port-to-Port Services",
      "Airport-to-Airport Services",
      "Cross Trade Shipments",
      "Buyers Consolidation",
      "Cargo Consolidation",
      "Purchase Order Management",
      "Vendor Coordination",
      "Shipment Planning",
      "Cargo Insurance Assistance",
      "Track & Trace Support",
      "Project Cargo Coordination",
    ],
    image: "/images/services/freight-forwarding.jpg",
    credit: "Logan Voss on Unsplash",
    creditHref: "https://unsplash.com/@loganvoss",
  },
  {
    num: "02",
    tag: "Import · Export · Compliance",
    title: "Customs Clearance",
    desc: "Simplifying Customs. Ensuring Compliance.",
    body: "Customs procedures can often be complex and time-sensitive. Our experienced team assists businesses in navigating documentation, regulatory requirements, and clearance procedures, helping minimize delays and ensuring compliance with applicable regulations.",
    items: [
      "Import Customs Clearance",
      "Export Customs Clearance",
      "Bill of Entry Processing",
      "Shipping Bill Processing",
      "Duty Assessment Assistance",
      "HS Code Classification",
      "Customs Documentation",
      "SEZ Documentation",
      "EOU Documentation",
      "DGFT Assistance",
      "Drawback Processing",
      "High Sea Sale Documentation",
      "Bonding & Ex-Bonding",
      "ATA Carnet Assistance",
      "Re-import / Re-export Documentation",
      "SVB Support",
      "Customs Compliance Advisory",
    ],
    image: "/images/services/customs-clearance.jpg",
    credit: "Yoav Aziz on Unsplash",
    creditHref: "https://unsplash.com/@yoavaziz",
  },
  {
    num: "03",
    tag: "Storage · Fulfilment",
    title: "Warehousing",
    desc: "Secure Storage Solutions That Support Your Supply Chain",
    body: "Efficient warehousing plays a critical role in inventory management and business continuity. Our warehousing solutions provide secure storage, organized inventory handling, and flexible space to meet changing business requirements.",
    items: [
      "Bonded Warehousing",
      "Non-Bonded Warehousing",
      "Inventory Management",
      "Pick & Pack",
      "Cross Docking",
      "Palletization",
      "Order Fulfilment",
      "Distribution Management",
      "Cargo Consolidation",
      "Deconsolidation",
      "Barcode Management",
      "Value Added Services",
      "Stock Monitoring",
    ],
    image: "/images/services/warehousing.jpg",
    credit: "Vida Huang on Unsplash",
    creditHref: "https://unsplash.com/@rebylulu",
  },
  {
    num: "04",
    tag: "Domestic · Last-Mile",
    title: "Transportation",
    desc: "Reliable Transportation You Can Count On",
    body: "Timely transportation is essential to keeping businesses moving. We provide dependable transportation solutions that connect suppliers, manufacturers, distributors, and customers through efficient logistics planning and execution.",
    items: [
      "Full Truck Load (FTL)",
      "Part Truck Load (PTL)",
      "Container Transportation",
      "ODC Transportation",
      "Break Bulk Cargo",
      "First Mile Pickup",
      "Last Mile Delivery",
      "Factory-to-Port Movement",
      "Port-to-Warehouse Movement",
      "Inter-State Transportation",
      "Dedicated Fleet Solutions",
      "Reverse Logistics",
      "Milk Run Distribution",
      "Time Critical Deliveries",
    ],
    image: "/images/services/transportation.jpg",
    credit: "Vitalii Onyshchuk on Unsplash",
    creditHref: "https://unsplash.com/@true_zuzu",
  },
  {
    num: "05",
    tag: "Yard · Equipment",
    title: "Container Handling",
    desc: "Efficient Container Management with Operational Precision",
    body: "From container movement to handling and coordination, we ensure smooth operations throughout the logistics process. Our experienced team works closely with clients and partners to optimize container handling while minimizing operational delays.",
    items: [
      "Empty Container Movement",
      "Laden Container Movement",
      "Container Yard Coordination",
      "ICD Coordination",
      "CFS Coordination",
      "Container Stuffing",
      "Container De-stuffing",
      "Seal Verification",
      "Container Inspection",
      "Port Coordination",
      "Equipment Planning",
    ],
    image: "/images/services/container-handling.jpg",
    credit: "Haris Illahi on Unsplash",
    creditHref: "https://unsplash.com/@harisillahi",
  },
  {
    num: "06",
    tag: "Advisory · Market Entry",
    title: "Export Consultancy",
    desc: "Helping Businesses Enter Global Markets with Confidence",
    body: "Exporting successfully requires more than transportation—it requires the right guidance. We support businesses by simplifying export procedures, helping them understand documentation requirements, compliance processes, logistics planning, and international trade practices.",
    items: [
      "Export process guidance",
      "Documentation support",
      "Logistics planning",
      "Trade compliance assistance",
      "Market readiness guidance",
      "End-to-end export coordination",
    ],
    image: "/images/services/export-consultancy.jpg",
    credit: "Ambre Estève on Unsplash",
    creditHref: "https://unsplash.com/@ambresteve",
  },
];

export const MARQUEE_SERVICE_NAMES = SERVICES.map((s) => s.title).concat([
  "Global Trade Solutions",
]);
